### ISSUE TITLE
Xrm.Page.data.process.addOnStageSelected not defined

### ISSUE THREAD

**Issue by daryllabar** [6ix4our/DefinitelyTyped#4]
CRM 7.1 added the addOnStageSelected method, but it's not in the xrm.d.ts file:
https://msdn.microsoft.com/en-us/library/dn817878.aspx#BKMK_addOnStageSelected

**Comment by daryllabar** [comment]
Also getSelectedStage isn't defined either:  https://msdn.microsoft.com/en-us/library/dn817878.aspx#BKMK_getSelectedStage

**Comment by daryllabar** [comment]
I can create this as a pull request if you want.  Just not sure if I should fork your branch, or the borisyankov/DefinitelyTyped?

**Comment by 6ix4our** [comment]
I accepted your merge to this fork.  :)  Thank you!

**Comment by daryllabar** [comment]
No Problem!
